version: "3.1"

services:

  php-dev:
    container_name: web_srv
    build: 
      context: .
      dockerfile: apache-srv.dockerfile
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./Backend:/var/www/html

  adminer:
    container_name: web_adminer
    image: adminer:latest
    restart: always
    ports:
    - 3000:8080
    environment:
      ADMINER_DESIGN: pepa-linha
